academia/core/urls.py
from django.urls import path
from .views import ErrorView, HomeView, PricingView, RegisterView, ProfileView, CoursesView, CourseCreateView, CourseEditView,CourseDeleteView,CoursEnrollmentView, StudentListMarkView, UpdateMarkView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # PÁGINA DE INICIO
    path('', HomeView.as_view(), name="home"),
    # PÄGINA DE PRECIOS
    path('pricing/', PricingView.as_view(), name="pricing"),
    # PAGINA DE LOGIN y REGISTRO
    path('register/', RegisterView.as_view(), name="register"),
    # PÁGINAS DE PERFIL: VISTA DE PERFIL - EDICIÓN DEL PERFIL
    path('profile/', login_required(ProfileView.as_view()), name="profile"),
    # PÁGINA QUE ADMINISTRA LOS CURSOS: LISTA DE CURSOS - ( CREACIÓN - EDICIÓN - ELIMINAR )
    path('courses/', CoursesView.as_view(), name="courses"),  
    path('courses/create/', login_required(CourseCreateView.as_view()), name="course_create"),
    path('error/', login_required(ErrorView.as_view()), name="error"),
    path('courses/<int:pk>/edit/', login_required(CourseEditView.as_view()), name="course_edit"),
    path("courses/<int:pk>/delete/", login_required(CourseDeleteView.as_view()), name="course_delete"),
    # INSCRIPCIÓN DE UN ALUMNO EN UN CURSO
    path("enroll_course/<int:course_id>/", login_required(CoursEnrollmentView.as_view()), name="enroll_course"),
    # PROFESOR AÑADIR NOTAS
    path("courses/<int:course_id>", login_required(StudentListMarkView.as_view()), name="student_list_mark"),
    path('courses/update_mark/<int:mark_id>/', login_required(UpdateMarkView.as_view()), name="update_mark"),
    
    
]

academia/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# CURSOS: ESTADS POSIBLES(STATUS) : EN ETAPA DE INSCRIPCION - EN DESARROLLO - FINALIZADO
class Course(models.Model):
    STATUS_CHOICES = [
        ('I', 'En etapa de inscripción'),
        ('P', 'En progreso'),
        ('F', 'Finalizado'),
    ]
    
    name = models.CharField(max_length=90, verbose_name='Nombre')
    description = models.TextField(blank=True, null=True, verbose_name='Descripción')
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': 'profesores'}, verbose_name='Profesor')
    class_quantity = models.PositiveIntegerField(default=0, verbose_name='Cantidad de clases')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='I', verbose_name='Estado')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
     
# INSCRIPCIONES   
class Registration(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='students_registration', limit_choices_to={'groups__name': 'estudiantes'}, verbose_name='Estudiante')
    enable = models.BooleanField(default=True, verbose_name='Alumno Regular')
    
    def __str__(self):
        return f'{self.student.username} - {self.course.name}'
    
    class Meta:
        verbose_name = 'Inscripción'
        verbose_name_plural = 'Inscripciones'

# ASISTENCIAS
class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='attendances', limit_choices_to={'groups__name': 'estudiantes'}, verbose_name='Estudiante')
    date = models.DateField(null=True, blank=True, verbose_name='Fecha')
    present = models.BooleanField(default=False, blank=True, null=True,verbose_name='Presente')
    
    
    def __str__(self):
        return f'Asistencia {self.id}'


    def update_registration_enable_status(self):
        course_instance = Course.objects.get(id=self.course.id)
        total_classes = course_instance.class_quantity
        # Como un select con where y count
        total_absences = Attendance.objects.filter(student=self.student, course=self.course, present=False).count()
        absences_percent = (total_absences / total_classes) * 100
        
        registration = Registration.objects.get(course=self.course, student=self.student)
        
        if absences_percent > 20:
            registration.enable = False
        else:
            registration.enable = True
            
        registration.save()
    
    
    class Meta:
        verbose_name = 'Asistencia'
        verbose_name_plural = 'Asistencias'
        

# CALIFICACIONES o NOTAS
class Mark(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': 'estudiantes'}, verbose_name='Estudiante')
    mark_1 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Nota 1')
    mark_2 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Nota 2')
    mark_3 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Nota 3')
    average = models.DecimalField(max_digits=3, decimal_places=1, null=True, blank=True, verbose_name='Promedio')
    
    def __str__(self):
        return f'Asistencia {self.id}'
    
    # Calcular el promedio
    def calculate_average(self):
        marks = [self.mark_1, self.mark_2, self.mark_3]
        valid_marks = [mark for mark in marks if mark is not None]
        if valid_marks:
            return sum(valid_marks) / len(valid_marks)
        return None

    def save(self, *args, **kwargs):
        # verifico si alguna nota cambio
        if self.mark_1 or self.mark_2 or self.mark_3:
            self.average = self.calculate_average()
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = 'Nota'
        verbose_name_plural = 'Notas'

@receiver(post_save, sender=Attendance)
@receiver(post_delete, sender=Attendance)
def update_registration_enable_status(sender, instance, **kwargs): # Puede llamarse de otra forma 
    instance.update_registration_enable_status()

academia/templates/profile/admin.html
<div>
    <h6>{{ group_name_singular | capfirst}}</h6>
</div>

academia/templates/profile/preceptor.html
<div>
    <h5>TODOS LOS CURSOS</h5>
    <div class="card text-bg-warning shadow mt-3 mb-3">
        <div class="card-header">CURSOS EN PROGRESO</div>
        <div class="card-body">
            {% if progress_courses %}
                <ul class="list-group">
                    {% for course in progress_courses %}
                        {% with enrollment_count=course.registration_set.count %}
                            <li class="list-group-item list-group-item-warning">
                                {{ course.name }}
                                <a href="" class="btn btn-sm btn-warning float-end">
                                    Asistencias
                                    <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                                </a>
                            </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
            <div class="alert alert-warning" role="alert">
                    No hay cursos en progreso hasta el momento
                </div>
            {% endif %}
        </div>
    </div>

    <div class="card text-bg-success shadow mb-3">
        <div class="card-header">CURSO EN ETAPA DE INSCRIPCIÓN</div>
        <div class="card-body">
            {% if inscription_courses %}
                <ul class="list-group">
                    {% for course in inscription_courses %}
                        {% with enrollment_count=course.registration_set.count %}   
                        <li class="list-group-item list-group-item-success">
                            {{ course.name }}
                            <a href="" class="btn btn-sm btn-success float-end">
                                {% if course.status == 'I' %}
                                    Consultar listado
                                {% endif %}
                                <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                            </a>
                        </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
                <div>
                    No hay inscripciones en este curso hasta el momento
                </div>
            {% endif %}
        </div>
    </div>

    <div class="card text-bg-danger shadow mb-3">
        <div class="card-header">CURSOS FINALIZADOS</div>
        <div class="card-body">
            {% if finalized_courses %}
                <ul class="list-group">
                    {% for course in finalized_courses %}
                        {% with enrollment_count=course.registration_set.count %}   
                        <li class="list-group-item list-group-item-danger">
                            {{ course.name }}
                            <a href="{% url 'student_list_mark' course.id %}" class="btn btn-sm btn-danger float-end">
                                {% if course.status == 'F' %}
                                    Consultar listado
                                {% endif %}
                                <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                            </a>
                        </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    No tiene Cursos finalizados asignados hasta el momento
                </div>
            {% endif %}
        </div>
    </div>

</div>

academia/templates/profile/profesor.html
<div>
    <h5>CURSOS ASIGNADOS</h5>
    <div class="card text-bg-warning shadow mt-3 mb-3">
        <div class="card-header">CURSOS EN PROGRESO</div>
        <div class="card-body">
            {% if progress_courses %}
                <ul class="list-group">
                    {% for course in progress_courses %}
                        {% with enrollment_count=course.registration_set.count %}
                            <li class="list-group-item list-group-item-warning">
                                {{ course.name }}
                                <a href="{% url 'student_list_mark' course.id %}" class="btn btn-sm btn-warning float-end">
                                    Agregar Notas
                                    <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                                </a>
                            </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-warning" role="alert">
                    No tiene Cursos en progreso asignados hasta el momento.
                </div>
            {% endif %}
        </div>
    </div>

    <div class="card text-bg-success shadow mb-3">
        <div class="card-header">CURSO EN ETAPA DE INSCRIPCIÓN</div>
        <div class="card-body">
            {% if inscription_courses %}
                <ul class="list-group">
                    {% for course in inscription_courses %}
                        {% with enrollment_count=course.registration_set.count %}   
                        <li class="list-group-item list-group-item-success">
                            {{ course.name }}
                            <a href="{% url 'student_list_mark' course.id %}" class="btn btn-sm btn-success float-end">
                                {% if course.status == 'I' %}
                                    Consultar listado
                                {% endif %}
                                <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                            </a>
                        </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-success" role="alert">
                    No hay inscripciones en este curso hasta el momento
                </div>
            {% endif %}
        </div>
    </div>

    <div class="card text-bg-danger shadow mb-3">
        <div class="card-header">CURSOS FINALIZADOS</div>
        <div class="card-body">
            {% if finalized_courses %}
                <ul class="list-group">
                    {% for course in finalized_courses %}
                        {% with enrollment_count=course.registration_set.count %}   
                        <li class="list-group-item list-group-item-danger">
                            {{ course.name }}
                            <a href="{% url 'student_list_mark' course.id %}" class="btn btn-sm btn-danger float-end">
                                {% if course.status == 'F' %}
                                    Consultar listado
                                {% endif %}
                                <span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
                            </a>
                        </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
            <div class="alert alert-danger" role="alert">
                    No tiene Cursos finalizados asignados hasta el momento
                </div>
            {% endif %}
        </div>
    </div>

</div>

academia/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-3">

        <div class="row">
            <div class="col-md-4">
                {% comment %} CARD DATOS DE PERFIL {% endcomment %}
                <div class="card border rounded-2 shadow p-3 mb-3">
                    <div class="card-body">
                        <img class="img-thumbnail rounded-circle mb-3" src="{{ user.profile.image.url }}" alt="{{ user.username }}" style="width: 100px;">
                        <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                        <h4><span class="badge {{ color }}">{{ group_name_singular | capfirst }}</span></h4>
                        <hr>
                        <p><strong>Nombre de usuario: </strong>{{ user.username }}</p>
                        <p><strong>Domicilio: </strong>{{ user.profile.address }}</p>
                        <p><strong>Localidad: </strong>{{ user.profile.location }}</p>
                        <p><strong>Teléfono: </strong>{{ user.profile.telephone }}</p>
                        <p><strong>Correo electrónico: </strong>{{ user.email }}</p>
                        <hr>
                        {% if group_name == 'administrativos' %}
                            <a class="btn btn-warning w-100" href="{% url 'admin:index' %}" >Ir al Admin</a>
                        {% endif %}
                        <button type="button" class="btn btn-outline-secondary w-100 mb-1" data-bs-toggle="modal" data-bs-target="#editProfileModal">
                            Editar Perfil
                        </button>
                        <form method="post" action="{% url 'logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger w-100">Cerrar sesión</button>
                        </form>                
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                {% comment %} Evaluar grupo al que pertene el usuario {% endcomment %}
                {% if group_name == 'estudiantes' %}
                    {% include "profile/students.html" %}
                {% elif group_name == 'profesores'  %}
                    {% include "profile/profesor.html"  %}
                {% elif group_name  == 'preceptores'   %}
                    {% include   "profile/preceptor.html"   %}
                {% elif group_name == 'administrativos'  %}
                    {% include  "profile/admin.html"  %}
                {% endif  %}
            </div>
        </div>
    </div>

    <div class="modal fade" id="editProfileModal" tabindex="-1" aria-labelledby="editProfileModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="editProfileModalLabel">Editar Perfil</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="d-flex">
                                <img class="mx-auto img-thumbnail rounded-circle mb-3" src="{{ user.profile.image.url }}" alt="{{ user.username }}" style="width: 100px;">
                            </div>
                            <div class="mb-3">
                                <label for="image">Imagen de Perfil</label>
                                <input class="form-control" type="file" name="image" id="image">
                            </div>
                            <div class="d-flex">
                                <div class="mb-3 mr-2">
                                    <label for="first_name">Nombre</label>
                                    <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}" id="first_name">
                                </div>
                                <div class="mb-3">
                                    <label for="last_name">Apellidos</label>
                                    <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}" id="last_name"></label>

                                </div>
                            </div>

                            <div class="d-flex">
                                <div class="mb-3 mr-2">
                                    <label for="telephone">Teléfono</label>
                                    <input type="text" class="form-control" name="telephone" value="{{ user.profile.telephone }}" id="telephone">
                                </div>
                                <div class="mb-3">
                                    <label for="email">Email</label>
                                    <input type="text" class="form-control" name="email" value="{{ user.email }}" disabled id="email"></label>

                                </div>
                            </div>

                            <div class="d-flex">
                                <div class="mb-3 mr-2">
                                    <label for="address">Dirección</label>
                                    <input type="text" class="form-control" name="address" value="{{ user.profile.address }}" id="address">
                                </div>
                                <div class="mb-3">
                                    <label for="location">Localidad</label>
                                    <input type="text" class="form-control" name="location" value="{{ user.profile.location }}" id="location"></label>

                                </div>
                            </div>
                            
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                            
                        </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    

{% endblock %}

academia/templates/profile/students.html
<div>
    <h5>CURSOS EN LOS QUE ESTÁS INSCRITOS</h5>
    {% if enrolled_courses %}
        <ul class="list-group">
            {% for course in enrolled_courses %}
            {% with enrollment_count=course.registration_set.count %}
                <li class="list-group-item">
                    {{ course.name }}
                    <a href="" class="btn btn-sm btn-warning float-end">
                        Consultar Evolución
                    </a>
                </li>
            {% endwith %}
            {% endfor %}
        </ul>
    {% else %}
        <div class="alert alert-primary" role="alert">
            Ud. no está inscrito en ningún curso.
        </div>
    {% endif %}
</div>